"""add system_id to users table

Revision ID: 3aa87677f0e5
Revises: 40d119d5d9b7
Create Date: 2026-03-18 14:53:29.138912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa87677f0e5'
down_revision = '40d119d5d9b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 使用 batch 模式处理 SQLite 的约束限制
    with op.batch_alter_table('users') as batch_op:
        # 添加 system_id 列
        batch_op.add_column(sa.Column('system_id', sa.String(length=36), nullable=True, comment='关联的系统ID（项目ID），为None表示全局用户'))
        # 删除旧的唯一索引
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_username')
        # 创建新的非唯一索引
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        # 创建 system_id 索引
        batch_op.create_index(batch_op.f('ix_users_system_id'), ['system_id'], unique=False)
        # 创建复合唯一约束
        batch_op.create_unique_constraint('uq_user_username_system', ['username', 'system_id'])
    
    # 注意：我们不删除那些 _model 表，因为它们可能包含数据
    # 这些表可能是旧的，但为了安全起见，保留它们
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('uq_user_username_system', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_system_id'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('system_id')
    # ### end Alembic commands ###