"""add system_id to users table

Revision ID: 3aa87677f0e5
Revises: 40d119d5d9b7
Create Date: 2026-03-18 14:53:29.138912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa87677f0e5'
down_revision = '40d119d5d9b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 简化版本：由于数据库可能已经处于正确状态，我们只执行必要的操作
    # 检查 system_id 列是否已存在
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'system_id' not in columns:
        # 添加 system_id 列
        op.add_column('users', sa.Column('system_id', sa.String(length=36), nullable=True, comment='关联的系统ID（项目ID），为None表示全局用户'))
    
    # 检查索引是否已存在
    indexes = inspector.get_indexes('users')
    index_names = [idx['name'] for idx in indexes]
    
    # 创建 system_id 索引（如果不存在）
    if 'ix_users_system_id' not in index_names:
        op.create_index(op.f('ix_users_system_id'), 'users', ['system_id'], unique=False)
    
    # 创建复合唯一约束（如果不存在）
    if 'uq_user_username_system' not in index_names:
        # 在 SQLite 中，唯一约束是通过创建唯一索引实现的
        op.create_unique_constraint('uq_user_username_system', 'users', ['username', 'system_id'])
    
    # 注意：我们不删除那些 _model 表，因为它们可能包含数据
    # 这些表可能是旧的，但为了安全起见，保留它们
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 简化版本：只删除我们添加的内容
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    indexes = inspector.get_indexes('users')
    index_names = [idx['name'] for idx in indexes]
    
    # 删除复合唯一约束
    if 'uq_user_username_system' in index_names:
        op.drop_constraint('uq_user_username_system', 'users', type_='unique')
    
    # 删除 system_id 索引
    if 'ix_users_system_id' in index_names:
        op.drop_index(op.f('ix_users_system_id'), table_name='users')
    
    # 删除 system_id 列
    if 'system_id' in columns:
        op.drop_column('users', 'system_id')
    # ### end Alembic commands ###