"""Initial migration

Revision ID: 40d119d5d9b7
Revises:
Create Date: 2026-03-15 18:07:04.388662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d119d5d9b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 system_model 表
    op.create_table('system_model',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='systemstatus'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_model_created_at'), 'system_model', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_model_name'), 'system_model', ['name'], unique=False)
    op.create_index(op.f('ix_system_model_status'), 'system_model', ['status'], unique=False)
    
    # 创建 block_model 表
    op.create_table('block_model',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('system_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ABORTED', name='blockstatus'), nullable=False),
        sa.ForeignKeyConstraint(['system_id'], ['system_model.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_model_created_at'), 'block_model', ['created_at'], unique=False)
    op.create_index(op.f('ix_block_model_name'), 'block_model', ['name'], unique=False)
    op.create_index(op.f('ix_block_model_priority'), 'block_model', ['priority'], unique=False)
    op.create_index(op.f('ix_block_model_status'), 'block_model', ['status'], unique=False)
    op.create_index(op.f('ix_block_model_system_id'), 'block_model', ['system_id'], unique=False)
    
    # 创建 feature_model 表
    op.create_table('feature_model',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('block_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('test_command', sa.Text(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'ABORTED', name='featurestatus'), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('current_retry', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['block_id'], ['block_model.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_model_block_id'), 'feature_model', ['block_id'], unique=False)
    op.create_index(op.f('ix_feature_model_created_at'), 'feature_model', ['created_at'], unique=False)
    op.create_index(op.f('ix_feature_model_name'), 'feature_model', ['name'], unique=False)
    op.create_index(op.f('ix_feature_model_status'), 'feature_model', ['status'], unique=False)
    
    # 创建 test_model 表
    op.create_table('test_model',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('feature_id', sa.String(length=36), nullable=False),
        sa.Column('command', sa.Text(), nullable=False),
        sa.Column('exit_code', sa.Integer(), nullable=True),
        sa.Column('stdout', sa.Text(), nullable=True),
        sa.Column('stderr', sa.Text(), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', name='teststatus'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['feature_id'], ['feature_model.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_model_created_at'), 'test_model', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_model_feature_id'), 'test_model', ['feature_id'], unique=False)
    op.create_index(op.f('ix_test_model_status'), 'test_model', ['status'], unique=False)
    
    # 创建 task_queue_model 表
    op.create_table('task_queue_model',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('test_id', sa.String(length=36), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ABORTED', name='taskqueuestatus'), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['test_id'], ['test_model.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_queue_model_created_at'), 'task_queue_model', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_queue_model_priority'), 'task_queue_model', ['priority'], unique=False)
    op.create_index(op.f('ix_task_queue_model_status'), 'task_queue_model', ['status'], unique=False)
    op.create_index(op.f('ix_task_queue_model_test_id'), 'task_queue_model', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_queue_model_test_id'), table_name='task_queue_model')
    op.drop_index(op.f('ix_task_queue_model_status'), table_name='task_queue_model')
    op.drop_index(op.f('ix_task_queue_model_priority'), table_name='task_queue_model')
    op.drop_index(op.f('ix_task_queue_model_created_at'), table_name='task_queue_model')
    op.drop_table('task_queue_model')
    
    op.drop_index(op.f('ix_test_model_status'), table_name='test_model')
    op.drop_index(op.f('ix_test_model_feature_id'), table_name='test_model')
    op.drop_index(op.f('ix_test_model_created_at'), table_name='test_model')
    op.drop_table('test_model')
    
    op.drop_index(op.f('ix_feature_model_status'), table_name='feature_model')
    op.drop_index(op.f('ix_feature_model_name'), table_name='feature_model')
    op.drop_index(op.f('ix_feature_model_created_at'), table_name='feature_model')
    op.drop_index(op.f('ix_feature_model_block_id'), table_name='feature_model')
    op.drop_table('feature_model')
    
    op.drop_index(op.f('ix_block_model_system_id'), table_name='block_model')
    op.drop_index(op.f('ix_block_model_status'), table_name='block_model')
    op.drop_index(op.f('ix_block_model_priority'), table_name='block_model')
    op.drop_index(op.f('ix_block_model_name'), table_name='block_model')
    op.drop_index(op.f('ix_block_model_created_at'), table_name='block_model')
    op.drop_table('block_model')
    
    op.drop_index(op.f('ix_system_model_status'), table_name='system_model')
    op.drop_index(op.f('ix_system_model_name'), table_name='system_model')
    op.drop_index(op.f('ix_system_model_created_at'), table_name='system_model')
    op.drop_table('system_model')
    
    # 删除枚举类型
    op.execute("DROP TYPE IF EXISTS taskqueuestatus")
    op.execute("DROP TYPE IF EXISTS teststatus")
    op.execute("DROP TYPE IF EXISTS featurestatus")
    op.execute("DROP TYPE IF EXISTS blockstatus")
    op.execute("DROP TYPE IF EXISTS systemstatus")
    # ### end Alembic commands ###