"""Initial migration

Revision ID: 40d119d5d9b7
Revises:
Create Date: 2026-03-15 18:07:04.388662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d119d5d9b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 system 表
    op.create_table('system',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='systemstatus'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_created_at'), 'system', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_name'), 'system', ['name'], unique=False)
    op.create_index(op.f('ix_system_status'), 'system', ['status'], unique=False)
    
    # 创建 block 表
    op.create_table('block',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('system_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ABORTED', name='blockstatus'), nullable=False),
        sa.ForeignKeyConstraint(['system_id'], ['system.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_created_at'), 'block', ['created_at'], unique=False)
    op.create_index(op.f('ix_block_name'), 'block', ['name'], unique=False)
    op.create_index(op.f('ix_block_priority'), 'block', ['priority'], unique=False)
    op.create_index(op.f('ix_block_status'), 'block', ['status'], unique=False)
    op.create_index(op.f('ix_block_system_id'), 'block', ['system_id'], unique=False)
    
    # 创建 feature 表
    op.create_table('feature',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('block_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('test_command', sa.Text(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'ABORTED', name='featurestatus'), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('current_retry', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['block_id'], ['block.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_block_id'), 'feature', ['block_id'], unique=False)
    op.create_index(op.f('ix_feature_created_at'), 'feature', ['created_at'], unique=False)
    op.create_index(op.f('ix_feature_name'), 'feature', ['name'], unique=False)
    op.create_index(op.f('ix_feature_status'), 'feature', ['status'], unique=False)
    
    # 创建 test 表
    op.create_table('test',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('feature_id', sa.String(length=36), nullable=False),
        sa.Column('command', sa.Text(), nullable=False),
        sa.Column('exit_code', sa.Integer(), nullable=True),
        sa.Column('stdout', sa.Text(), nullable=True),
        sa.Column('stderr', sa.Text(), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', name='teststatus'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_created_at'), 'test', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_feature_id'), 'test', ['feature_id'], unique=False)
    op.create_index(op.f('ix_test_status'), 'test', ['status'], unique=False)
    
    # 创建 task_queue 表
    op.create_table('task_queue',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('test_id', sa.String(length=36), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ABORTED', name='taskqueuestatus'), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_queue_created_at'), 'task_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_queue_priority'), 'task_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_task_queue_status'), 'task_queue', ['status'], unique=False)
    op.create_index(op.f('ix_task_queue_test_id'), 'task_queue', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_queue_test_id'), table_name='task_queue')
    op.drop_index(op.f('ix_task_queue_status'), table_name='task_queue')
    op.drop_index(op.f('ix_task_queue_priority'), table_name='task_queue')
    op.drop_index(op.f('ix_task_queue_created_at'), table_name='task_queue')
    op.drop_table('task_queue')
    
    op.drop_index(op.f('ix_test_status'), table_name='test')
    op.drop_index(op.f('ix_test_feature_id'), table_name='test')
    op.drop_index(op.f('ix_test_created_at'), table_name='test')
    op.drop_table('test')
    
    op.drop_index(op.f('ix_feature_status'), table_name='feature')
    op.drop_index(op.f('ix_feature_name'), table_name='feature')
    op.drop_index(op.f('ix_feature_created_at'), table_name='feature')
    op.drop_index(op.f('ix_feature_block_id'), table_name='feature')
    op.drop_table('feature')
    
    op.drop_index(op.f('ix_block_system_id'), table_name='block')
    op.drop_index(op.f('ix_block_status'), table_name='block')
    op.drop_index(op.f('ix_block_priority'), table_name='block')
    op.drop_index(op.f('ix_block_name'), table_name='block')
    op.drop_index(op.f('ix_block_created_at'), table_name='block')
    op.drop_table('block')
    
    op.drop_index(op.f('ix_system_status'), table_name='system')
    op.drop_index(op.f('ix_system_name'), table_name='system')
    op.drop_index(op.f('ix_system_created_at'), table_name='system')
    op.drop_table('system')
    
    # 删除枚举类型
    op.execute("DROP TYPE IF EXISTS taskqueuestatus")
    op.execute("DROP TYPE IF EXISTS teststatus")
    op.execute("DROP TYPE IF EXISTS featurestatus")
    op.execute("DROP TYPE IF EXISTS blockstatus")
    op.execute("DROP TYPE IF EXISTS systemstatus")
    # ### end Alembic commands ###